// integrations/svelte-bubbles/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  import { layoutMessages, prepareMessages, type BubbleMessage, type BubbleMetric } from './lib/pretextBubbles'

  const messages: BubbleMessage[] = [
    { id: 'm1', speaker: 'system', text: 'Svelte should still respect the same rule: prepare once for text changes, layout for width changes.' },
    { id: 'm2', speaker: 'user', text: 'The integration is framework-specific, but the architectural split is the same across every app.' },
    { id: 'm3', speaker: 'system', text: 'This is where the skill stops being empty guidance and starts looking like a reusable project boundary.' },
  ]

  let frame: HTMLDivElement
  let metrics: BubbleMetric[] = []

  onMount(() => {
    let observer: ResizeObserver | null = null

    async function start() {
      const prepared = await prepareMessages(messages)
      observer = new ResizeObserver(entries => {
        const width = entries[0]?.contentRect.width ?? frame.clientWidth
        metrics = layoutMessages(prepared, width)
      })
      observer.observe(frame)
      metrics = layoutMessages(prepared, frame.clientWidth)
    }

    void start()

    return () => observer?.disconnect()
  })
</script>

<main class="page">
  <section class="hero">
    <p class="eyebrow">Svelte + TypeScript</p>
    <h1>Pretext Bubbles</h1>
    <p class="intro">This version keeps the integration small: one preload step, one resize observer, and typed layout output.</p>
  </section>
  <section class="panel">
    <header class="panel-header">
      <div>
        <h2>Svelte Integration</h2>
        <p>Resize the frame. The bubbles update from Pretext metrics rather than remeasuring text after paint.</p>
      </div>
      <div class="badge">prepare + layout</div>
    </header>
    <div bind:this={frame} class="frame">
      <div class="list">
        {#each metrics as message (message.id)}
          <article class={`bubble bubble--${message.speaker}`} style={`min-height:${message.height}px`}>
            <p>{message.text}</p>
            <footer>{message.lineCount} lines</footer>
          </article>
        {/each}
      </div>
    </div>
  </section>
</main>

// integrations/react-bubbles/src/App.tsx
import { usePretextBubbles, type BubbleMessage } from './usePretextBubbles'

const messages: BubbleMessage[] = [
  { id: 'm1', speaker: 'system', text: 'React prepares each message once, then reuses the prepared handles during width changes.' },
  { id: 'm2', speaker: 'user', text: 'The hook owns the split between prepare and layout so components do not drift back to DOM measurement.' },
  { id: 'm3', speaker: 'system', text: 'This is the kind of integration boundary a real project needs: typed, framework-aware, and explicit about the hot path.' },
]

export default function App() {
  const { frameRef, metrics } = usePretextBubbles(messages)

  return (
    <main className="page">
      <section className="hero">
        <p className="eyebrow">React + TypeScript</p>
        <h1>Pretext Bubbles</h1>
        <p className="intro">
          A real React integration should isolate Pretext inside a hook, wait for fonts, and relayout from width changes
          without reparsing text on every render.
        </p>
      </section>
      <section className="panel">
        <header className="panel-header">
          <div>
            <h2>Hook-Based Integration</h2>
            <p>Resize the frame. The bubble metrics update from cached prepared text.</p>
          </div>
          <div className="badge">usePretextBubbles</div>
        </header>
        <div ref={frameRef} className="frame">
          <div className="list">
            {metrics.map(message => (
              <article
                key={message.id}
                className={`bubble bubble--${message.speaker}`}
                style={{ minHeight: `${message.height}px` }}
              >
                <p>{message.text}</p>
                <footer>{message.lineCount} lines</footer>
              </article>
            ))}
          </div>
        </div>
      </section>
    </main>
  )
}
